server:
  port: 32388
management:
  endpoint:
    shutdown:
      enabled: true
    restart:
      enabled: true
config:
  packageName: com.generation.entity
  repoPackageName: com.generation.repo
  outputPath: target/generated-sources/java
